name: Hello world git action
on:
  push:
    paths:
      - "!README.md"
      - "!docs/**"
      - "**.ts"
    branches: [main, develop]
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Xin Chao, today is $TODAY
